
DROP TABLE IF EXISTS claims_transactions CASCADE;
DROP TABLE IF EXISTS medications CASCADE;
DROP TABLE IF EXISTS procedures CASCADE;
DROP TABLE IF EXISTS conditions CASCADE;
DROP TABLE IF EXISTS encounters CASCADE;
DROP TABLE IF EXISTS payers CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS patients CASCADE;

CREATE TABLE patients (
    Id UUID PRIMARY KEY,
    BIRTHDATE DATE,
    DEATHDATE DATE,
    SSN VARCHAR(11),
    DRIVERS VARCHAR(20),
    PASSPORT VARCHAR(20),
    PREFIX VARCHAR(10),
    FIRST VARCHAR(50),
    MIDDLE VARCHAR(50),
    LAST VARCHAR(50),
    SUFFIX VARCHAR(10),
    MAIDEN VARCHAR(50),
    MARITAL CHAR(1),
    RACE VARCHAR(50),
    ETHNICITY VARCHAR(50),
    GENDER CHAR(1),
    BIRTHPLACE VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTY VARCHAR(50),
    FIPS VARCHAR(10),
    ZIP VARCHAR(10),
    LAT DECIMAL(9,6),
    LON DECIMAL(9,6),
    HEALTHCARE_EXPENSES DECIMAL(12,2),
    HEALTHCARE_COVERAGE DECIMAL(12,2),
    INCOME DECIMAL(12,2)
);

CREATE TABLE organizations (
    Id UUID PRIMARY KEY,
    NAME VARCHAR(200),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP VARCHAR(10),
    LAT DECIMAL(9,6),
    LON DECIMAL(9,6),
    PHONE VARCHAR(100),
    REVENUE DECIMAL(15,2),
    UTILIZATION INTEGER
);

CREATE TABLE payers (
    Id UUID PRIMARY KEY,
    NAME VARCHAR(200),
    OWNERSHIP VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE_HEADQUARTERED VARCHAR(50),
    ZIP VARCHAR(10),
    PHONE VARCHAR(20),
    AMOUNT_COVERED DECIMAL(15,2),
    AMOUNT_UNCOVERED DECIMAL(15,2),
    REVENUE DECIMAL(15,2),
    COVERED_ENCOUNTERS INTEGER,
    UNCOVERED_ENCOUNTERS INTEGER,
    COVERED_MEDICATIONS INTEGER,
    UNCOVERED_MEDICATIONS INTEGER,
    COVERED_PROCEDURES INTEGER,
    UNCOVERED_PROCEDURES INTEGER,
    COVERED_IMMUNIZATIONS INTEGER,
    UNCOVERED_IMMUNIZATIONS INTEGER,
    UNIQUE_CUSTOMERS INTEGER,
    QOLS_AVG DECIMAL(5,2),
    MEMBER_MONTHS INTEGER
);

CREATE TABLE encounters (
    Id UUID PRIMARY KEY,
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    ORGANIZATION UUID NOT NULL,
    PROVIDER UUID,
    PAYER UUID,
    ENCOUNTERCLASS VARCHAR(50),
    CODE VARCHAR(20),
    DESCRIPTION TEXT,
    BASE_ENCOUNTER_COST DECIMAL(12,2),
    TOTAL_CLAIM_COST DECIMAL(12,2),
    PAYER_COVERAGE DECIMAL(12,2),
    REASONCODE VARCHAR(20),
    REASONDESCRIPTION TEXT
);

CREATE INDEX idx_patient_timeline ON encounters(PATIENT, START);
CREATE INDEX idx_org_encounters ON encounters(ORGANIZATION, ENCOUNTERCLASS);
CREATE INDEX idx_encounter_type ON encounters(ENCOUNTERCLASS);


CREATE TABLE conditions (
    START DATE NOT NULL,
    STOP DATE,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID,
    SYSTEM VARCHAR(100),
    CODE VARCHAR(20),
    DESCRIPTION TEXT
);

CREATE INDEX idx_patient_conditions ON conditions(PATIENT);
CREATE INDEX idx_condition_code ON conditions(CODE);
CREATE INDEX idx_patient_condition_timeline ON conditions(PATIENT, START);

CREATE TABLE procedures (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID,
    SYSTEM VARCHAR(100),
    CODE VARCHAR(20),
    DESCRIPTION TEXT,
    BASE_COST DECIMAL(12,2),
    REASONCODE VARCHAR(20),
    REASONDESCRIPTION TEXT
);

CREATE INDEX idx_procedure_encounter ON procedures(ENCOUNTER);
CREATE INDEX idx_procedure_code ON procedures(CODE);
CREATE INDEX idx_procedure_patient ON procedures(PATIENT);

CREATE TABLE medications (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    PAYER UUID,
    ENCOUNTER UUID,
    CODE VARCHAR(20),
    DESCRIPTION TEXT,
    BASE_COST DECIMAL(12,2),
    PAYER_COVERAGE DECIMAL(12,2),
    DISPENSES INTEGER,
    TOTALCOST DECIMAL(12,2),
    REASONCODE VARCHAR(20),
    REASONDESCRIPTION TEXT
);

CREATE INDEX idx_patient_medications ON medications(PATIENT, START);
CREATE INDEX idx_medication_encounter ON medications(ENCOUNTER);

CREATE TABLE claims_transactions (
    ID UUID PRIMARY KEY,
    CLAIMID UUID,
    CHARGEID INTEGER,
    PATIENTID UUID NOT NULL,
    TYPE VARCHAR(50),
    AMOUNT DECIMAL(12,2),
    METHOD VARCHAR(50),
    FROMDATE TIMESTAMP,
    TODATE TIMESTAMP,
    PLACEOFSERVICE UUID,
    PROCEDURECODE VARCHAR(20),
    MODIFIER1 VARCHAR(10),
    MODIFIER2 VARCHAR(10),
    DIAGNOSISREF1 INTEGER,
    DIAGNOSISREF2 INTEGER,
    DIAGNOSISREF3 INTEGER,
    DIAGNOSISREF4 INTEGER,
    UNITS INTEGER,
    DEPARTMENTID INTEGER,
    NOTES TEXT,
    UNITAMOUNT DECIMAL(12,2),
    TRANSFEROUTID INTEGER,
    TRANSFERTYPE VARCHAR(50),
    PAYMENTS DECIMAL(12,2),
    ADJUSTMENTS DECIMAL(12,2),
    TRANSFERS DECIMAL(12,2),
    OUTSTANDING DECIMAL(12,2),
    APPOINTMENTID UUID,
    LINENOTE TEXT,
    PATIENTINSURANCEID UUID,
    FEESCHEDULEID INTEGER,
    PROVIDERID UUID,
    SUPERVISINGPROVIDERID UUID
);
CREATE INDEX idx_patient_procedure_claims ON claims_transactions(PATIENTID, PROCEDURECODE);
CREATE INDEX idx_denial_analysis ON claims_transactions(PROCEDURECODE, OUTSTANDING);
CREATE INDEX idx_claims_encounter ON claims_transactions(APPOINTMENTID);
CREATE INDEX idx_transaction_type ON claims_transactions(TYPE);
